### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by rickdoesburg** [AndreasBackx/StyleSorter#10]
Whenever I call the StyleSorter using CMD + SHIFT + P it returns

Traceback (most recent call last):
  File "Parser in /Users/rickdoesburg/Library/Application Support/Sublime Text 3/Installed Packages/StyleSorter.sublime-package", line 25, in run
  File "Parser in /Users/rickdoesburg/Library/Application Support/Sublime Text 3/Installed Packages/StyleSorter.sublime-package", line 187, in format
  File "Parser in /Users/rickdoesburg/Library/Application Support/Sublime Text 3/Installed Packages/StyleSorter.sublime-package", line 253, in order
  File "Parser in /Users/rickdoesburg/Library/Application Support/Sublime Text 3/Installed Packages/StyleSorter.sublime-package", line 278, in order
IndexError: string index out of range

**Comment by AndreasBackx** [comment]
Could you provide the file on which you tried to use StyleSorter?

**Comment by rickdoesburg** [comment]
//----- BREADCRUMBS -----\\
.breadcrumbs {
	overflow: hidden;
	padding: 0 0 1em;
	margin: 0 0 1.5em 0;
	border-bottom: 1px solid $dzw_dgrey;

	.breadcrumb-item {
		display: inline-block;

		list-style-type: none;
	}

	.breadcrumb-item-link {
		@include font-size (1.2);

		padding-right: .5em;

		color: $txtcolor;

		&:after {
			@include sprite-dimensions($icons, chevron-black-right-small);

			display: inline-block;

			margin-left: .5em;

			background-image: sprite-url($icons);
			background-position: sprite-position($icons, chevron-black-right-small);

			content: "";
		}
	}

	&:last-child a:after {
		content: "";
	}
}


  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 513, in __getitem__
    raise IndexError()
IndexError

**Comment by AndreasBackx** [comment]
I added the code markdown to your comment, please do so yourself in the future. What does this do in that file even?

> File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 513, in getitem
> raise IndexError()
> IndexError

**Comment by rickdoesburg** [comment]
Thanks, haven't used Markdown that much. I'm not sure what you're getting at?
